# Generated by Django 5.0.3 on 2024-04-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_image_alter_userreviews_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseBook',
        ),
    ]
