# Generated by Django 5.0.3 on 2024-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_purchasebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
