# Generated by Django 5.0.3 on 2024-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_borrowed_books'),
        ('books', '0004_delete_purchasebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='borrowed_books',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, null=True, to='books.books'),
        ),
    ]
