# Generated by Django 5.0.3 on 2024-04-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_borrowed_books_and_more'),
        ('books', '0005_alter_books_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, to='books.books'),
        ),
    ]
