# Generated by Django 5.0.3 on 2024-04-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_borrowed_books_and_more'),
        ('books', '0004_delete_purchasebook'),
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
